### ISSUE TITLE
Thumbnail creation fails with ffmpeg

### ISSUE THREAD

**Issue by sziraqui** [sziraqui/node-file-server#1]
Issue caught after commit 562a0d4ceb5560813281a15fc588186be45fe873
Complete log:

```
{ ChildProcessError: Command failed: ffmpeg -y -i 'C:\Users\sonu\Documents\szi\node-file-server\uploads\SampleVideo_1280x720_1mb.mp4' -ss 00:00:01 -t 00:00:03 -r 8 -vf "scale=200:114" -an -c:v libx264 'C:\Users\sonu\AppData\Local\Temp\video-thumbnail-part1528GLYOYyRvXN37.mp4'
ffmpeg version N-90315-gf706cdda56 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56.  9.100 / 56.  9.100
  libavcodec     58. 14.100 / 58. 14.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 13.100 /  7. 13.100
  libswscale      5.  0.102 /  5.  0.102
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
'C:\Users\sonu\Documents\szi\node-file-server\uploads\SampleVideo_1280x720_1mb.mp4': Invalid argument
 `ffmpeg -y -i 'C:\Users\sonu\Documents\szi\node-file-server\uploads\SampleVideo_1280x720_1mb.mp4' -ss 00:00:01 -t 00:00:03 -r 8 -vf "scale=200:114" -an -c:v libx264 'C:\Users\sonu\AppData\Local\Temp\video-thumbnail-part1528GLYOYyRvXN37.mp4'` (exited with error code 1)
    at callback (C:\Users\sonu\Documents\szi\node-file-server\node_modules\child-process-promise\lib\index.js:33:27)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  name: 'ChildProcessError',
  code: 1,
  childProcess:
   { ChildProcess: { [Function: ChildProcess] super_: [Object] },
     fork: [Function],
     _forkChild: [Function],
     exec: [Function],
     execFile: [Function],
     spawn: [Function],
     spawnSync: [Function: spawnSync],
     execFileSync: [Function: execFileSync],
     execSync: [Function: execSync] },
  stdout: '',
  stderr: 'ffmpeg version N-90315-gf706cdda56 Copyright (c) 2000-2018 the FFmpeg developers\r\n  built with gcc 7.3.0 (GCC)\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth\r\n  libavutil      56.  9.100 / 56.  9.100\r\n  libavcodec     58. 14.100 / 58. 14.100\r\n  libavformat    58. 10.100 / 58. 10.100\r\n  libavdevice    58.  2.100 / 58.  2.100\r\n  libavfilter     7. 13.100 /  7. 13.100\r\n  libswscale      5.  0.102 /  5.  0.102\r\n  libswresample   3.  0.101 /  3.  0.101\r\n  libpostproc    55.  0.100 / 55.  0.100\r\n\'C:\\Users\\sonu\\Documents\\szi\\node-file-server\\uploads\\SampleVideo_1280x720_1mb.mp4\': Invalid argument\r\n' }
```

**Comment by sziraqui** [comment]
After commit ce1db75aa06cb03455d0c7e95949c835f24f5908 -
The error message does not appear but still there is no png file in thumbs directory.
A new file with file name "{" is created in root
The  created thumbs directory is read only even after chmod 777.
This could be windows specific issue.
